# BiPay GitHub Actions CI/CD

name: bipay-backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r apps/api/requirements.txt
      - name: Run tests
        run: |
          pytest apps/api
      - name: Build Docker image
        run: |
          docker build -t bipay-api ./apps/api
      - name: Deploy to Render/Railway
        run: echo "Deploy step here (see README)"
